/** Minimal structured night payload for local webhook testing. */
export function buildDemoTipTraqReport(reportDate: string): Record<string, unknown> {
  return {
    report_date: reportDate,
    algorithm_version: 'demo-structured-v1',
    recording_start: '22:40',
    recording_end: '07:05',
    trt_minutes: 505,
    signal_quality_pct: 91,
    sleep_onset: '23:05',
    sleep_offset: '06:55',
    sleep_latency_minutes: 18,
    tst_minutes: 402,
    waso_minutes: 38,
    sleep_efficiency_pct: 86,
    rem_duration_minutes: 88,
    rem_pct_tst: 21.9,
    nrem_duration_minutes: 314,
    first_rem_onset: '00:42',
    ahi: 3.2,
    rdi: 4.1,
    odi_3pct: 2.8,
    odi_4pct: 1.9,
    t90_pct: 0.4,
    min_spo2: 92,
    mean_spo2: 96,
    hypoxic_burden: 0.6,
    event_count: 4,
    mean_pr: 58,
    min_pr: 49,
    max_pr: 74,
    sns_pct: 42,
    pns_pct: 58,
    snoring_minutes: 12,
  }
}
